### ISSUE TITLE
Contributing on Windows - Testing Issue

### ISSUE THREAD

**Issue by danrzeppa** [brianc/node-sql#133]
I've forked the repo and when I attempt to run the tests on my Windows 7 computer I get the following error:

> > sql@0.27.0 test X:\github\node-sql
> > NODE_ENV=test ./node_modules/.bin/mocha
> 
> 'NODE_ENV' is not recognized as an internal or external command,
> operable program or batch file.
> npm ERR! weird error 1
> npm ERR! not ok code 0

Just for giggles, I removed the "NODE_ENV=test" part since that doesn't work for exporting environment variables in windows which left me with "./node_modules/.bin/mocha". When running like this I get this error:

> > sql@0.27.0 test X:\github\node-sql
> > ./node_modules/.bin/mocha
> 
> '.' is not recognized as an internal or external command,
> operable program or batch file.
> npm ERR! weird error 1
> npm ERR! not ok code 0

After reading https://github.com/isaacs/npm/issues/2576, I removed the " ./node_modules/.bin/" and was left with "mocha" as my command. Things seem to work a bit better, but still some errors:

> > sql@0.27.0 test X:\github\node-sql
> > mocha
> 
>  ...........................................................
>  ...........
> X:\github\node-sql\node_modules.bin\mocha:2
> basedir=`dirname "$0"`
>        ^
> SyntaxError: Unexpected token ILLEGAL
>    at Module._compile (module.js:439:25)
>    at Object.Module._extensions..js (module.js:474:10)
>    at Module.load (module.js:356:32)
>    at Function.Module._load (module.js:312:12)
>    at Function.Module.runMain (module.js:497:10)
>    at startup (node.js:119:16)
>    at node.js:901:3
> 
> Command failed:
> X:\github\node-sql\node_modules.bin\mocha:2
> basedir=`dirname "$0"`
>        ^
> SyntaxError: Unexpected token ILLEGAL
>    at Module._compile (module.js:439:25)
>    at Object.Module._extensions..js (module.js:474:10)
>    at Module.load (module.js:356:32)
>    at Function.Module._load (module.js:312:12)
>    at Function.Module.runMain (module.js:497:10)
>    at startup (node.js:119:16)
>    at node.js:901:3
> 
> .................................................
>  ............................................................
>  ............................................................
>  ............................................................
>  ............................................................
>  ............................................................
>  ............................................................
>  ............................................................
>  ............................................................
>  .
> 
>  600 passing (279ms)

**Comment by lebolo** [comment]
This is pretty late, but I just ran into this problem and Google led me here. So if it helps others, to get the tests to run on Windows, I modified the package.json to use

    "scripts": {
      "test": "NODE_ENV=test ./node_modules/.bin/mocha",
      "test-win": "set NODE_ENV=test && node_modules\\.bin\\mocha"
    }

Then run `npm run-script test-win` instead.
